ARG OPENCV_VERSION=4.10.0
ARG RUST_TOOLCHAIN=stable

FROM debian:bookworm AS opencv-builder

ARG OPENCV_VERSION

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    cmake \
    curl \
    git \
    libatlas-base-dev \
    libavcodec-dev \
    libavformat-dev \
    libdc1394-dev \
    libeigen3-dev \
    libgstreamer-plugins-base1.0-dev \
    libgstreamer1.0-dev \
    libgtk-3-dev \
    libjpeg-dev \
    libopenexr-dev \
    libopenjp2-7-dev \
    libpng-dev \
    libswscale-dev \
    libtbb-dev \
    libtiff-dev \
    libwebp-dev \
    ninja-build \
    pkg-config \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp

RUN curl -fsSL "https://github.com/opencv/opencv/archive/${OPENCV_VERSION}.tar.gz" -o opencv.tar.gz && \
    tar -xzf opencv.tar.gz && \
    curl -fsSL "https://github.com/opencv/opencv_contrib/archive/${OPENCV_VERSION}.tar.gz" -o opencv_contrib.tar.gz && \
    tar -xzf opencv_contrib.tar.gz

RUN cmake -S "/tmp/opencv-${OPENCV_VERSION}" -B /tmp/opencv-build -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr/local \
    -DOPENCV_EXTRA_MODULES_PATH="/tmp/opencv_contrib-${OPENCV_VERSION}/modules" \
    -DBUILD_TESTS=OFF \
    -DBUILD_PERF_TESTS=OFF \
    -DBUILD_EXAMPLES=OFF \
    -DBUILD_opencv_apps=OFF \
    -DBUILD_JAVA=OFF \
    -DBUILD_opencv_python2=OFF \
    -DBUILD_opencv_python3=OFF \
    -DWITH_IPP=ON \
    -DWITH_TBB=ON \
    -DWITH_GTK=ON \
    -DWITH_GSTREAMER=ON \
    -DWITH_FFMPEG=ON && \
    cmake --build /tmp/opencv-build --parallel && \
    cmake --install /tmp/opencv-build && \
    rm -rf /tmp/opencv-build /tmp/opencv.tar.gz /tmp/opencv_contrib.tar.gz "/tmp/opencv-${OPENCV_VERSION}" "/tmp/opencv_contrib-${OPENCV_VERSION}"


FROM golang:1.24-bookworm

ARG OPENCV_VERSION
ARG RUST_TOOLCHAIN

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    clang \
    cmake \
    curl \
    exiftool \
    git \
    libatlas-base-dev \
    libavcodec59 \
    libavformat59 \
    libdc1394-25 \
    libeigen3-dev \
    libgstreamer-plugins-base1.0-0 \
    libgstreamer1.0-0 \
    libgtk-3-0 \
    libjpeg62-turbo \
    libopenexr-3-1-30 \
    libopenjp2-7 \
    libpng16-16 \
    libswscale6 \
    libtbb12 \
    libtiff6 \
    libwebp7 \
    libclang-dev \
    make \
    pkg-config \
    zlib1g \
    && rm -rf /var/lib/apt/lists/*

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain "${RUST_TOOLCHAIN}"

COPY --from=opencv-builder /usr/local /usr/local

WORKDIR /workspace

ENV CGO_ENABLED=1
ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/lib64/pkgconfig
ENV LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64
ENV PATH=/root/.cargo/bin:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV OPENCV_VERSION=${OPENCV_VERSION}
ENV RUSTUP_HOME=/root/.rustup
ENV CARGO_HOME=/root/.cargo

RUN mkdir -p /usr/local/lib/pkgconfig && \
    libs="$(find /usr/local/lib -maxdepth 1 -name 'libopencv_*.so' -printf '%f\n' | sed -e 's/^lib//' -e 's/\.so$//' | sort | sed 's/^/-l/' | tr '\n' ' ')" && \
    cat > /usr/local/lib/pkgconfig/opencv4.pc <<EOF
prefix=/usr/local
exec_prefix=\${prefix}
libdir=\${exec_prefix}/lib
includedir=\${prefix}/include/opencv4

Name: OpenCV
Description: Open Source Computer Vision Library
Version: ${OPENCV_VERSION}
Libs: -L\${libdir} ${libs}
Cflags: -I\${includedir}
EOF

RUN ldconfig

CMD ["/bin/bash"]
